### ISSUE TITLE
Can't sign messages using hardware wallet (trezor)

### ISSUE THREAD

**Issue by slingncrypto** [00labs/huma-dapp#205] opened 2023-03-22 02:57 UTC
On Goerli network, when attempting to Get Test USDC and prompted to sign message using metamask (w/ hw wallet)

Error: Forbidden Key Path

I think its related to EIP-712 signature support but just a guess.

**Comment by slingncrypto** [comment] 2023-03-22 03:00
works fine when settings -> prompt is enabled on the device, nvm

**Comment by shan-57blocks** [comment] 2023-04-04 07:29
Good to know that you found the cause. Will close this issue.

**Closed by shan-57blocks** 2023-04-04 07:29 UTC
